version: "3"

services:
    web:
        image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.5.1
        command: ["/start.sh"]
        environment:
            CONVOY_API_VERSION: ${CONVOY_API_VERSION}
            CONVOY_HOST: ${CONVOY_HOST}
            CONVOY_DB_HOST: ${CONVOY_DB_HOST}
            CONVOY_DB_USERNAME: ${POSTGRESQL_USERNAME}
            CONVOY_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
            CONVOY_DB_DATABASE: ${POSTGRESQL_DATABASE}
            CONVOY_DB_OPTIONS: ${POSTGRESQL_OPTIONS}
            CONVOY_DB_MAX_OPEN_CONN: ${POSTGRESQL_MAX_CONNECTIONS}
            CONVOY_REDIS_HOST: redis_server
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "wget -q --spider hooks.dev.qorlabs.io/health"]
            interval: 5s
            timeout: 15s
            retries: 3
            start_period: 5s
        depends_on:
            postgres:
                condition: service_healthy
            redis_server:
                condition: service_healthy

    worker:
        image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.5.1
        command: ["./cmd", "worker"]
        environment:
            CONVOY_API_VERSION: ${CONVOY_API_VERSION}
            CONVOY_HOST: ${CONVOY_HOST}
            CONVOY_DB_HOST: ${CONVOY_DB_HOST}
            CONVOY_DB_USERNAME: ${POSTGRESQL_USERNAME}
            CONVOY_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
            CONVOY_DB_DATABASE: ${POSTGRESQL_DATABASE}
            CONVOY_DB_OPTIONS: ${POSTGRESQL_OPTIONS}
            CONVOY_DB_MAX_OPEN_CONN: ${POSTGRESQL_MAX_CONNECTIONS}
            CONVOY_REDIS_HOST: redis_server
        restart: unless-stopped
        depends_on:
            web:
                condition: service_healthy

    ingest:
        image: docker.cloudsmith.io/convoy/convoy/frain-dev/convoy:v24.5.1
        command: ["./cmd", "ingest"]
        environment:
            CONVOY_API_VERSION: ${CONVOY_API_VERSION}
            CONVOY_HOST: ${CONVOY_HOST}
            CONVOY_DB_HOST: ${CONVOY_DB_HOST}
            CONVOY_DB_USERNAME: ${POSTGRESQL_USERNAME}
            CONVOY_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
            CONVOY_DB_DATABASE: ${POSTGRESQL_DATABASE}
            CONVOY_DB_OPTIONS: ${POSTGRESQL_OPTIONS}
            CONVOY_DB_MAX_OPEN_CONN: ${POSTGRESQL_MAX_CONNECTIONS}
            CONVOY_REDIS_HOST: redis_server
        restart: unless-stopped
        depends_on:
            web:
                condition: service_healthy
    postgres:
        image: bitnami/postgresql:latest
        restart: unless-stopped
        environment:
            POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
            POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
            POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
            POSTGRESQL_MAX_CONNECTIONS: ${POSTGRESQL_MAX_CONNECTIONS}
            POSTGRESQL_SHARED_PRELOAD_LIBRARIES: pg_stat_statements
        volumes:
          - postgresql_master_data:/bitnami/postgresql

    redis_server:
        image: redis:alpine
        restart: unless-stopped
        volumes:
          - redis_data:/data

volumes:
    postgresql_master_data:
        external: true
    redis_data:
        external: true
